export const RESULTADO_GERAL_ID = '1bM-PoeZ7HDMLfuFP-zBp5HaHWndLnqkOXFXlYxxn4K0'

export const DEFAULT_SETTINGS = {
  usdRate:     5.30,
  aliquota:    0.155,
  metaPiso:    30000,
  metaStretch: 40000,
}

export const DEFAULT_OFFERS = [
  {
    id: 'reconquista',
    name: 'Código da Reconquista',
    status: 'active',
    color: '#2E75B6',
    resultSheetId: '1bM-PoeZ7HDMLfuFP-zBp5HaHWndLnqkOXFXlYxxn4K0',
    resultTab:     'CódigoReconquista',
    metaSheetId:   '1w8nfXFygWpAQknI_mXflutfxUViDBc7OU8LifWIXAGA',
    metaTab:       'Página1',
    metaCurrency:  'USD',
    frontProduct:  'El Código de la ReConquista 2.0',
    otherProducts: ['Reset Emocional de la Ex 2.0', 'Acelerador de Reconquista de tu Ex 10x'],
  },
  {
    id: 'secreto',
    name: 'Secreto de Ellas',
    status: 'active',
    color: '#7B3F9E',
    resultSheetId: '1bM-PoeZ7HDMLfuFP-zBp5HaHWndLnqkOXFXlYxxn4K0',
    resultTab:     'Secreto de Ellas',
    metaSheetId:   '1b-xKLJvmxz5vm6zQXWbv-YkGq_ExE9waPLklhOOuIkk',
    metaTab:       'Página1',
    metaCurrency:  'USD',
    frontProduct:  'El Secreto de Ellas',
    otherProducts: ['El Secreto de Ellas 2.0', 'Tiempo de Conexión 2.0'],
  },
  {
    id: 'instinto_mulher',
    name: 'Instinto Mulher',
    status: 'active',
    color: '#C55A11',
    resultSheetId: '1bM-PoeZ7HDMLfuFP-zBp5HaHWndLnqkOXFXlYxxn4K0',
    resultTab:     'Instinto - Mulher',
    metaSheetId:   '1ICpz12XWQTOszgV8gMRlSmygGEXyGJLhEp7yTUAMDq4',
    metaTab:       'Página1',
    metaCurrency:  'USD',
    frontProduct:  'El Manual del Instinto primitivo',
    otherProducts: ['Guía del Instinto de Protección', 'El Reinicio del Instinto'],
  },
  {
    id: 'correntes',
    name: 'Correntes (Las 7 Llaves)',
    status: 'active',
    color: '#1A7A4A',
    resultSheetId: '1bM-PoeZ7HDMLfuFP-zBp5HaHWndLnqkOXFXlYxxn4K0',
    resultTab:     'Correntes',
    metaSheetId:   '1BcsZ-H6rDHSbQZfv1qR2UOZWW2_adY5ciOkBL7NEaAI',
    metaTab:       'Página1',
    metaCurrency:  'USD',
    frontProduct:  'Cadena de las 7 llaves',
    otherProducts: ['El Reinicio Interior', 'Acelerador del Ritual 10X'],
  },
  {
    id: 'libido',
    name: 'Libido Oculta',
    status: 'active',
    color: '#C00000',
    resultSheetId: '1bM-PoeZ7HDMLfuFP-zBp5HaHWndLnqkOXFXlYxxn4K0',
    resultTab:     'Libido Oculta',
    metaSheetId:   '124yoxh_fbQqoOUFlFcDDQ2b-kIwtxc3n3_6ZkFP1qs0',
    metaTab:       'Página1',
    metaCurrency:  'USD',
    frontProduct:  'Protocolo Libido Oculta',
    otherProducts: ['Método Masaje Relajante', 'Tiempo máximo'],
  },
]

export const MES_COL_MAP = {
  data:            0,
  corrente_oracao: 1,
  cod_reconquista: 2,
  instinto_mulher: 3,
  secreto_dellas:  4,
  rafa_todos:      5,
  libido_oculta:   6,
  resultado_dia:   8,
  faturamento:     10,
  gasto:           11,
  roi:             12,
  margem_lucro:    13,
}
